# Generated by Django 5.0 on 2024-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taches',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
